### ISSUE TITLE
[BadMethodCallException] Call to undefined method [package]

### ISSUE THREAD

**Issue by fcaivano** [cartalyst/converter#16]
The docs here:
https://cartalyst.com/manual/converter/2.0#configuration

State that we should use
```
php artisan vendor:publish
```
to publish the configuration file.

But i get:
```
[BadMethodCallException]            
  Call to undefined method [package]
```
On laravel 5... I've seen issue #11 but i assume as per the docs that the package already supports L5...

What might be the problem?

Or how can i move the config manually to keep working?

**Comment by brunogaspar** [comment]
There's a typo on the documentation, change the Composer requirement to `2.0.*` instead of `1.1.*`, run `composer update` and the `vendor:publish` will work.
