### ISSUE TITLE
Convert Celcius to Farenheit

### ISSUE THREAD

**Issue by oliveiraped** [cartalyst/converter#17]
Hi I am using package, and i wnat to convert celsius to Farenheit so i did this in the config 

'temperature' => array(

            'celcius' => array(
                'format' => '1 °C',
                'unit'   => 1,
            ),

            'fahrenheit' => array(
                'format' => '1 °F',
                'unit'   => 32,
            ),

Bu to the conversion celcius to Farenheit his 
T(°F) = T(°C) × 9/5 + 32

How i can do this ? 

Can i put on the Farenheit unit this "9/5 + 32"

**Comment by oliveiraped** [comment]
'temperature' => array(

            'celcius' => array(
                'format' => '1 °C',
                'unit'   => 1.00,
            ),

            'fahrenheit' => array(
                'format' => '32.00 °F',
                'unit'   => (1.8)+32.00,
            ),

        ),

Hi this this and it worked ! Thanks Great package !!

**Comment by brunogaspar** [comment]
Awesome, we're about to run a few tests with a similar approach :)
