### ISSUE TITLE
Zero value returns a previously processed number

### ISSUE THREAD

**Issue by benjam-es** [cartalyst/converter#18]
I have a helper function which I use to output prices in my project. Behind the scenes we have a currency selector which I use with the function. Leaving no currency set just results in the value (for instance 100) being returned with the correct formatting $100.00.

If I use the helper on 100 it outputs $100.00
If I then use the helper on 350 it output $350.00

If i then use the helper on 0 it outputs $350.00

Something is not working correctly for it to retain and output the previous converter result

**Comment by brunogaspar** [comment]
I think we just need to add a `!== null` check here https://github.com/cartalyst/converter/blob/2.0/src/Converter.php#L151

Can you see if by doing that works fine?

**Comment by brunogaspar** [comment]
Pushed fix, give it a go and let me know so i can tag it or improve it somewhere else.

**Comment by benjam-es** [comment]
This update didn't pull in despite my project composer having the following

            "cartalyst/converter": "2.0.*",

**Comment by brunogaspar** [comment]
It's not tagged, hence i asked you to test it :)
