### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by alecritson** [cartalyst/converter#29]
### Expected behaviour

Should be able to install this package on Laravel 9

### Actual behaviour

`illuminate/cache` and `illuminate/filesystem` are locked to `^8.0`.

Happy to do a PR if this isn't already being worked on.

**Comment by suwardany** [comment]
Hi,

Just pushed a version to the master branch that adds support for Laravel 9.

We will tag it within the next few days, in the mean time, you can install it using `"cartalyst/converter": "^7.0"` if you're minimum stability is set to `dev`

Thank you for offering to help out with a PR, we appreciate it.

Let us know if you run into anything or have any further questions.

**Comment by glennjacobs** [comment]
Any update on when this will be tagged? Thanks.

**Comment by suwardany** [comment]
Just tagged it!
