### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by glennjacobs** [cartalyst/converter#30]
Will you be supporting Laravel 10 soon?

Happy to do a PR if it would help.

Thanks

**Comment by brunogaspar** [comment]
Absolutely, i forgot about this one :)

**Comment by glennjacobs** [comment]
Made a start for you

https://github.com/cartalyst/converter/pull/31

:-)

**Comment by brunogaspar** [comment]
oh, it's already done and tagged, but thank you!!

**Comment by glennjacobs** [comment]
That was quick :-)

I notice the tests don't cover PHP 8.2 though?
